platform:
  - x64

image: Visual Studio 2015

environment:
  global:
    CYG_ROOT: C:/cygwin64
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_CACHE: C:/cygwin64/var/cache/setup
    OCAML_PORT: msvc64
    ARTEFACTS: no
    FLEXDLL_VERSION: 0.43
    FLEXDLL_WARN_ERROR: true
  matrix:
    - OCAMLBRANCH: 3.11
    - OCAMLBRANCH: 3.12
      OCAMLREV: 1
    - OCAMLBRANCH: 4.00
    - OCAMLBRANCH: 4.01
    - OCAMLBRANCH: 4.02
    - OCAMLBRANCH: 4.03
      SKIP_OCAML_TEST: no
    - OCAMLBRANCH: 4.04
    - OCAMLBRANCH: 4.05
    - OCAMLBRANCH: 4.06
    - OCAMLBRANCH: 4.07
    - OCAMLBRANCH: 4.08
    - OCAMLBRANCH: 4.09
    - OCAMLBRANCH: 4.10
    - OCAMLBRANCH: 4.11
    - OCAMLBRANCH: 4.12
      OCAML_PORT: mingw
      ARTEFACTS: yes
      MSVS_PREFERENCE: SDK7.0
    - OCAMLBRANCH: 4.13
    - OCAMLBRANCH: 4.14
      SKIP_OCAML_TEST: no
    - OCAMLBRANCH: 5.0
      OCAML_PORT: mingw64
    - OCAMLBRANCH: 5.1
      OCAML_PORT: mingw64
    - OCAMLBRANCH: 5.2
      OCAML_PORT: mingw64
    - OCAMLBRANCH: 5.3
      OCAML_PORT: mingw64
      SKIP_OCAML_TEST: no
    - OCAMLBRANCH: trunk
      OCAML_PORT: mingw64
      SKIP_OCAML_TEST: no
  OCAMLROOT: C:/OCaml

cache:
  - C:/OCaml

install:
  # Make sure the Cygwin path comes before the Git one (otherwise
  # cygpath behaves crazily), but after the MSVC one.
  - set Path=C:\cygwin64\bin;%OCAMLROOT%\bin;C:\flexdll;%Path%
  - '%CYG_ROOT%\bin\bash -lc "cygcheck -dc cygwin"'
  - if exist "%CYG_ROOT%\setup-x86_64.exe" del "%CYG_ROOT%\setup-x86_64.exe"
  - appveyor DownloadFile "https://cygwin.com/setup-x86_64.exe" -FileName "%CYG_ROOT%\setup-x86_64.exe"
  - '"%CYG_ROOT%\setup-x86_64.exe" --quiet-mode --no-shortcuts --no-startmenu --no-desktop --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages unzip,zip > nul'
  - '%CYG_ROOT%\bin\bash -lc "zip --version" > nul || "%CYG_ROOT%\setup-x86_64.exe" --quiet-mode --no-shortcuts --no-startmenu --no-desktop --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --upgrade-also > nul'
  - '%CYG_ROOT%\bin\bash -lc "cygcheck -dc cygwin"'
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
  - appveyor DownloadFile "https://github.com/ocaml/flexdll/archive/%FLEXDLL_VERSION%.tar.gz" -FileName "flexdll.tar.gz"
  - appveyor DownloadFile "https://github.com/ocaml/flexdll/releases/download/%FLEXDLL_VERSION%/flexdll-bin-%FLEXDLL_VERSION%.zip" -FileName "flexdll.zip"
  - appveyor DownloadFile "https://raw.githubusercontent.com/ocaml/ocaml/trunk/tools/msvs-promote-path" -FileName "msvs-promote-path"

build_script:
  - "%CYG_ROOT%/bin/bash -lc \"echo 'eval $($APPVEYOR_BUILD_FOLDER/msvs-promote-path)' >> ~/.bash_profile\""
  - '%CYG_ROOT%/bin/bash -lc "$APPVEYOR_BUILD_FOLDER/appveyor_build.sh"'

test: off
